travis:
  secure:
    BINSTAR_TOKEN: j4ip3Tlz88IDI+N0TlPp9vcdtExz+5TLvjpgFP3LZfd2c7cK0gvn6TlwhLjBPNPXVtEu1Hw97NoQnVz8swU4YB6JWTBKH6FdpUZfkO/DNKIjub4pViqrwIhkaVbhCw3HWaavrFw9z6RiCInqTF003MkRSHs4tD0vsvRyj0xFm9ePzPMSW5Q8ezIicad/xOcaLYZ3k8vwjCfk0qtjGE8jQQMVtCecjLD21zj7oflAHoWmE4EpJfvsConlTj48Ua69hFxW3FOJtqizshaHgcoywYp/RdwYhAt4aFeHGEgI3KskxYdewyEc6bYep4+6Rsru19asTDpHwHRfCcWeLUKLYKTAY7PUx+zwc3FU+YqkbYer6xGlCnkhqKuOnuX51AP2TrhVICKp4gFZU7rc3gM852lMAvRCxGENBCUfMlxoLrrEVJy7aGYWmSf+J8f1l+nCATQIekXPG/80pKDOBFew3Jq5yYEGrPn7qGKuX8N1kX1Kah5UttARqPfWYmMLKQm0omNV/9EliLapo+HweTxHcrrsF3k0HZmjV/V4aEFKmx9DmmNWGRGfrcqGSF8vS865U86gx8WKPSSCOQDOKLJKujwm/jkaywn4MmlfpwjSrsPJwN/+Ytq+HRmVsjyfDgNkcBp7PbBh2HY/8kGwriI9EZ+uWmb5mHFytfI3BlCPI3c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
