travis:
  secure:
    BINSTAR_TOKEN: SzNfpauwy3m2J0l//RTw1iUVSKqGakGcTDmQ8/voQ+9LFQQqwfmXbuwrRNvw9qyJeVuyFYq+44q9ouJ2r+VFCLcl2RzGtgWEB08Ga8EN0tzcaGwkCa4/2Ldm9G7KM1q4fP5lzZeL5+Imvtz3PRmvPfV4W6mQX4vRa2zk1fHq57ZwNnDd7BrScg99AZMAXDwo6fAghLKpOM7AgYTQhOYtVtrhx0UoGnqfmiTO+9CUymzuzaj158SrwwmncaWYqGBHAiJJK5d47iHs9XfcQiZwECygglAK9GuZkxyU1HP8Lj/uobMjBEWypvvVpTnvdG7vmH4FCDkDFmCwOp+Ym88pqB2Iczerzr8fyY4cN0fo2IYCFPpvqghdjD8D2ZDhHP3DEEgZR/I10bzmezW+/lRhGuu9gPE2fhoiF+kiUgtG7A+aZ1ZzRonPFb7R04q9hI/5srhJYFo57sDusCLBImr6FYh9igRa9+OZZgAmvPPJaHcf50DEEe4h6CUEJ60/+jmSMis7Rk818rYOplQICh5iRDHvsdMk1FLy8FVN4aXAo7m10cxN6BhKl3AYgVW+P6/wtqoeE2zvYRktihdI2Pe+VO0BHLOycBOeu0Oc1BLQqv8X9Gl9FGPvB8gTVkkcGgT8ZeKbQ4emiX/MTi+u3BW0Ic3hI93MnKFXbYoWZKCvkpM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
